[features]
seeds = false
skip-lint = false
[programs.devnet]
og_vault = "9pQFAH6qKdWcRXme1Wg7iZN27MwbPWTBAMJtKAQZPFyH"

[workspace]
repository = "https://github.com/chaingame-v1/og_vault.git"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/neo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
