[features]
seeds = false
skip-lint = false
[programs.devnet]
og_vault = "4vDCnxn3hMvNsKbRNMapuktpHYjka9Jv49Vzoq1uNMV2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/neo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
